[pytest]
markers =
    regression:
    smoke: Most critical tests
    search: Search service
    notifications: Notification service
    working: currently in debug
    post: Post service
    comment: Comment service
    likes:
    flaky
    auth
    feed
    messages
    login
    register
    moderation
    testing
    users
    positive
    negative
    comments
    admin
    bookmarks
    follows
    upload
testpaths = tests
pythonpath=.
addopts=
    -p no:warnings
    -sv
    --alluredir=allure-results
;    -m smoke
    --clean-alluredir