[pytest]
markers =
    regression:
    smoke: Most critical tests
    search: Search service
    notifications: Notification service
    working: currently in debug
    post: Post service
    comment: Comment service
    like:
    flaky
    registration
    feed
    messages
    login
    register
    moderation
    testing
    positive
    comments

testpaths = tests
pythonpath=.
addopts=
    -p no:warnings
    -sv
    --alluredir=allure-results
;    -m smoke
    --clean-alluredir